### ISSUE TITLE
Home Assistant Core Update 2023.11.1

### ISSUE THREAD

**Issue by matomatusov** [peterturza/home-assistant-jablotron-futura#3]
Ahoj,
po update Home Assistant Core  na 2023.11.1 prestali fungovať entity Futury. 

 Výpis zo Systému - Log
------------------------------------------------------------------------------------------------------------------------
Tato chyba pochází z vlastní integrace.

Logger: custom_components.jablotron_futura
Source: helpers/update_coordinator.py:290
Integration: Jablotron Futura (documentation)
First occurred: 23:33:51 (11 occurrences)
Last logged: 23:38:47

Unexpected error fetching jablotron_futura data:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 246, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jablotron_futura/futura.py", line 70, in sync
    await self.authorize()
  File "/config/custom_components/jablotron_futura/futura.py", line 66, in authorize
    raise ApiAuthError
custom_components.jablotron_futura.errors.ApiAuthError

--------------------------------------------------------------------------------------------------------

Tato chyba pochází z vlastní integrace.

Logger: custom_components.jablotron_futura.futura
Source: custom_components/jablotron_futura/futura.py:65
Integration: Jablotron Futura (documentation)
First occurred: 23:33:51 (11 occurrences)
Last logged: 23:38:47

<ClientResponse(https://api.jablonet.net/api/1.9/userAuthorize.json) [400 Bad Request]> <CIMultiDictProxy('Server': 'nginx', 'Date': 'Sat, 04 Nov 2023 22:35:05 GMT', 'Content-Type': 'application/json', 'Content-Length': '169', 'Connection': 'keep-alive', 'Etag': '"65454948-a9"', 'Content-Type': 'application/json')>
<ClientResponse(https://api.jablonet.net/api/1.9/userAuthorize.json) [400 Bad Request]> <CIMultiDictProxy('Server': 'nginx', 'Date': 'Sat, 04 Nov 2023 22:35:26 GMT', 'Content-Type': 'application/json', 'Content-Length': '169', 'Connection': 'keep-alive', 'Etag': '"65454948-a9"', 'Content-Type': 'application/json')>
<ClientResponse(https://api.jablonet.net/api/1.9/userAuthorize.json) [400 Bad Request]> <CIMultiDictProxy('Server': 'nginx', 'Date': 'Sat, 04 Nov 2023 22:36:06 GMT', 'Content-Type': 'application/json', 'Content-Length': '169', 'Connection': 'keep-alive', 'Etag': '"65454948-a9"', 'Content-Type': 'application/json')>
<ClientResponse(https://api.jablonet.net/api/1.9/userAuthorize.json) [400 Bad Request]> <CIMultiDictProxy('Server': 'nginx', 'Date': 'Sat, 04 Nov 2023 22:37:26 GMT', 'Content-Type': 'application/json', 'Content-Length': '169', 'Connection': 'keep-alive', 'Etag': '"65454948-a9"', 'Content-Type': 'application/json')>
<ClientResponse(https://api.jablonet.net/api/1.9/userAuthorize.json) [400 Bad Request]> <CIMultiDictProxy('Server': 'nginx', 'Date': 'Sat, 04 Nov 2023 22:38:47 GMT', 'Content-Type': 'application/json', 'Content-Length': '169', 'Connection': 'keep-alive', 'Etag': '"65454948-a9"', 'Content-Type': 'application/json')>

![image](https://github.com/peterturza/home-assistant-jablotron-futura/assets/129114957/8b86d5a8-af60-4e61-b633-7c4cbd7c3f26)

![image](https://github.com/peterturza/home-assistant-jablotron-futura/assets/129114957/19324007-3154-4f96-933f-b45bd8f08869)

**Comment by peterturza** [comment]
Prosím, aktualizujte na najnovšiu verziu 0.1.1 commit 5d845c64bee0af0011c9feb7433834d7b4992624
